replicaCount: 2
image:
  repository: your-docker-repo/reactjs-dashboard
  pullPolicy: Always
  tag: "latest"
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: reactjs-dashboard.yourdomain.com
      paths:
        - path: "/"
  tls: []

