apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-website
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nextjs-website
  template:
    metadata:
      labels:
        app: nextjs-website
    spec:
      containers:
        - name: nextjs-website
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-website
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: nextjs-website
